mythdoor/apps/account/urls.py
from django.conf.urls import *
from django.views.generic import RedirectView

from mythdoor.apps.account import views
from mythdoor.apps.account import forms

urlpatterns = [
    url(r"^signup$", views.signup_request, name="signup"),
    url(r"^signup/$",RedirectView.as_view(url='/accounts/signup',permanent=False)),
    url(r"^signup/(?P<confirmation_key>\w+)$", views.signup_complete,name="signup_complete"),

    url(r"^login$", views.login, name="login"),
    url(r"^login/$",RedirectView.as_view(url='/accounts/login',permanent=False)),

    url(r"^logout$", views.logout, name="logout"),
    url(r"^logout/$",RedirectView.as_view(url='/accounts/logout',permanent=False)),

    url(r"^password/change$", views.password_change,name="change_password"),
    url(r"^password/set$", views.password_set, name="set_password"),

    url(r"^password/reset$", views.password_reset,name="reset_password"),
    url(r"^password/reset/$", RedirectView.as_view(url='/accounts/password/reset',permanent=False)),
    url(r"^password/reset/done$", views.password_reset_done,name="reset_password_done"),
    url(r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)$",views.password_reset_from_key,name="reset_password_from_key"),
]

mythdoor/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls import handler404, handler500
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from tastypie.api import Api

from mythdoor import settings
from mythdoor.apps.api.autocomplete import AutocompleteResource
from mythdoor.apps.api.email import EmailResource

#from djrill import DjrillAdminSite

#admin.site = DjrillAdminSite()
admin.autodiscover()

v1_api = Api(api_name='v1')
v1_api.register(AutocompleteResource())
v1_api.register(EmailResource())

urlpatterns = [
    # Admin URL
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/defender/', include('defender.urls')), # defender admin

    # Auth
    url(r'^account/', include("mythdoor.apps.account.urls")),

    # Haystack app URL
    url(r'^search/', include("mythdoor.apps.search.urls")),

    url(r'^ajax/', include("mythdoor.apps.ajax.urls")),

    # API
    url(r'^api/', include(v1_api.urls)),

    # mythdoor URL
    url(r'^$', include('mythdoor.apps.main.urls')),
    url(r'^user/',include('mythdoor.apps.member.urls')),
    url(r'^post/',include('mythdoor.apps.post.urls')),
    url(r'^photo/',include('mythdoor.apps.photo.urls')),
    url(r'^about/',include('mythdoor.apps.about.urls')),

    url(r'^i18n/', include('django.conf.urls.i18n')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "mythdoor.apps.main.views.handler404"
handler500 = "mythdoor.apps.main.views.handler500"

mythdoor/apps/account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.shortcuts import render_to_response, get_object_or_404, redirect, render
from django.utils.translation import pgettext, ugettext_lazy as _, ugettext
from django.contrib.auth.tokens import default_token_generator as token_generator
from django.core.urlresolvers import reverse
from django.utils.http import int_to_base36
from django.contrib.auth import authenticate
from django.db.models import Q
from django.template.loader import render_to_string

from mythdoor.apps.member.helper import get_user_common_info
from mythdoor.apps.account.utils import perform_login, random_token
from mythdoor.apps.main.models import SignupRequest, Email, UserProfile
from mythdoor.apps.main.models import UserCredential, UserConnectionRequest, Company, Notification
from mythdoor.apps.account.tasks import analyze_signup_request
from mythdoor.apps.main.constants import EMPTY_STRING, CREDENTIAL_PROFESSIONAL, CREDENTIAL_OTHERS
from mythdoor.apps.main.constants import COMPLETED_STATUS, TRUE, FALSE
from mythdoor.apps.app_helper import check_key_not_blank
from mythdoor.apps.mailer.tasks import send_email
from mythdoor.settings import WEBSITE_URL
from mythdoor.apps.app_settings import NOTIFICATION_SNIPPET_TEMPLATE
from mythdoor.apps.account import settings as app_settings
from mythdoor.apps.account.utils import email_address_exists, generate_unique_username, valid_email_or_none

import logging

logger = logging.getLogger(__name__)

class UserForm(forms.Form):

    def __init__(self, user=None, *args, **kwargs):
        self.user = user
        super(UserForm, self).__init__(*args, **kwargs)


class SetPasswordField(forms.CharField):

	def clean(self, value):
		value = super(SetPasswordField, self).clean(value)
		min_length = app_settings.PASSWORD_MIN_LENGTH
		if len(value) < min_length:
			raise forms.ValidationError(_("Password must be a minimum of {0} "
										  "characters.").format(min_length))
		return value


class LoginForm(forms.Form):

	email = forms.EmailField(label=_("Email"),max_length=60,widget=forms.TextInput(attrs={'placeholder': 'Email','class': "form-control"}))
	password = forms.CharField(label=_("Password"),widget=forms.PasswordInput(attrs={'placeholder':"Password", "class": "form-control"}))

	def user_credentials(self):
		"""
		Provides the credentials required to authenticate the user for
		login.
		"""
		credentials = {
		  "email": self.cleaned_data["email"],
		  "password": self.cleaned_data["password"]
		}
		return credentials

	def clean(self):
		if self._errors:
			return
		user = authenticate(**self.user_credentials())
		if user:
			if user.is_active:
				self.user = user
			else:
				raise forms.ValidationError(_("This account is currently"
											  " inactive."))
		else:
			error = _("The e-mail address and/or password you specified"
						  " are not correct.")
			raise forms.ValidationError(error)
		return self.cleaned_data

	def login(self, request, redirect_url=None):
		ret = perform_login(request, self.user,
							email_verification=app_settings.EMAIL_VERIFICATION,
							redirect_url=redirect_url)
		request.session.set_expiry(60 * 60 * 24 * 7 * 3)
		return ret


class SignupRequestForm(forms.Form):
	email = forms.EmailField(label=_("Email"),max_length=60,widget=forms.TextInput(attrs={'placeholder': 'Email','class': "form-control"}))

	def clean_email(self):
		value = self.cleaned_data["email"]
		if valid_email_or_none(value) == None:
			raise forms.ValidationError(_("Invalid email"))
		elif email_address_exists(value):
			raise forms.ValidationError(_("A user is already registered"
									  " with this e-mail address."))
		return value

	def save(self, request):
		email_address = self.cleaned_data['email']
		signup_request = None
		signup_requests = SignupRequest.objects.filter(email=email_address,request_status="pending")
		confirmation_key = random_token([email_address])
		if len(signup_requests) == 0:
			signup_request = SignupRequest.objects.create(
				email=email_address,
				confirmation_key=confirmation_key
			)
		else:
			signup_request = signup_requests[0]
			confirmation_key = signup_request.confirmation_key
			if len(signup_requests) > 1:
				SignupRequest.objects.exclude(unique_id=signup_request.unique_id).delete()

		activate_url = '%s%s%s' % (WEBSITE_URL, '/account/signup/', confirmation_key)
		context = {"activate_url": activate_url}
		email = Email.objects.create(to_emails=email_address,email_template='signup_request_activation',context_data=str(context))
		analyze_signup_request.delay(signup_request.unique_id,email.unique_id)


class SignupCompleteForm(forms.Form):

	request_id = forms.CharField(required=False, max_length=100, widget=forms.HiddenInput())
	is_company_email = forms.CharField(required=False)
	company = forms.CharField(label=_("Company"),required=False,widget=forms.TextInput(attrs={'class': "form-control","required":"required"}))
	occupation = forms.CharField(label=_("Occupation"),required=False,widget=forms.TextInput(attrs={'class': "form-control"}))
	password1 = SetPasswordField(label=_("Password*"),widget=forms.PasswordInput(attrs={'placeholder':"Password", "class": "form-control","required":"required"}))
	password2 = forms.CharField(label=_("Confirm Password*"),widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password','class': "form-control","required":"required"}))
	request_approve_email = forms.CharField(label=_("Approver Email"),required=False,widget=forms.TextInput(attrs={'class': "form-control"}))
	connection_message = forms.CharField(label=_("Message"),required=False,widget=forms.Textarea(attrs={'class': "form-control","rows":"3"}))
	connection_relationship = forms.CharField(label=_("Comnection Relationship"),required=False,widget=forms.TextInput(attrs={'placeholder': 'Friend/Parent/Children','class': "form-control"}))
	name_initial = forms.CharField(label=_("Initial*"),max_length=2,widget=forms.TextInput(attrs={'placeholder': 'Your initial (maximum 2 character)','class': "form-control", "required": "required"}))
	preferred_email = forms.CharField(label=_("Preferred Email"),required=False,widget=forms.TextInput(attrs={'class': "form-control"}))

	def clean(self):
		super(SignupCompleteForm, self).clean()
		if "password1" in self.cleaned_data and "password2" in self.cleaned_data:
			if self.cleaned_data["password1"] != self.cleaned_data["password2"]:
				raise forms.ValidationError(_("You must type the same password each time."))

		if "is_company_email" in self.cleaned_data and self.cleaned_data['is_company_email'] == TRUE:
			if check_key_not_blank(self.cleaned_data,"company") == False:
				raise forms.ValidationError(_("You must provide company name if your email is company email"))
		return self.cleaned_data

	def clean_request_approve_email(self):
		if check_key_not_blank(self.cleaned_data,"request_approve_email"):
			value = self.cleaned_data["request_approve_email"]
			exist_users = UserProfile.objects.filter(user__email=value).exclude(email_type="normal")
			if len(exist_users) == 0:
				raise forms.ValidationError(_("There is no authorized user with that email. Please try another one"))
			return value
		return EMPTY_STRING

	def clean_preferred_email(self):
		if check_key_not_blank(self.cleaned_data,"preferred_email"):
			value = self.cleaned_data["preferred_email"]
			if valid_email_or_none(value) == None:
				raise forms.ValidationError(_("Invalid email"))
			elif email_address_exists(value):
				raise forms.ValidationError(_("A user already used this preferred email"))
			return value
		return EMPTY_STRING

	def clean_connection_relationship(self):
		if check_key_not_blank(self.cleaned_data,"request_approve_email"):
			if check_key_not_blank(self.cleaned_data,"connection_relationship") == False:
				raise forms.ValidationError(_("You have to specify your relationship with your connection if you request the approval"))
			return self.cleaned_data['connection_relationship']
		return EMPTY_STRING

	def save(self, request):
		data = self.cleaned_data
		try:
			signup_request = get_object_or_404(SignupRequest,unique_id=data['request_id'])
			email = signup_request.email
			email_type = signup_request.signup_email_type
			username = generate_unique_username([email,"user"])
			user = User.objects.create(username=username,email=email)
			user.set_password(data['password1'])
			credential = UserCredential()
			if email_type == "company":
				credential.company = signup_request.suggest_company
				credential.credential_type = CREDENTIAL_PROFESSIONAL
				if check_key_not_blank(data,"occupation"):
					credential.credential_additional_info = data['occupation']
			else:
				if "is_company_email" in data and data['is_company_email'] == TRUE:
					signup_request.signup_email_type = "company_pending"
					company_name = data['company']
					email_domain = signup_request.email[signup_request.email.index("@")+1:]
					company = Company.objects.create(name=company_name,email_domain=email_domain,is_verified=False)
					credential.company = company
					credential.credential_type = CREDENTIAL_OTHERS
					if check_key_not_blank(data,"occupation"):
						credential.credential_additional_info = data['occupation']
				else:
					signup_request.signup_email_type = "others"
					credential.credential_type = CREDENTIAL_OTHERS
					if check_key_not_blank(data,"request_approve_email"):
						request_approve_email = data['request_approve_email']
						try:
							approve_user = User.objects.get(email=request_approve_email)
							connection_relationship = data['connection_relationship']
							message = data['connection_message'] if check_key_not_blank(data,"connection_message") else EMPTY_STRING
							if approve_user.userprofile.email_type == "company":
								UserConnectionRequest.objects.create(request_user=user,connection_relationship=connection_relationship,
															approve_user=approve_user,connection_type="professional",message=message)

								context = {

mythdoor/assets/templates/sites/apps/account/page/main.jinja.html
{% extends base_template %}

{% block main_section %}
<div id="auth_section" class="container">
	<div id="instruction_section" class='row'>
		<div class="panel panel-default">
			<div class="panel-heading align-center">
				Account Type Instruction
			</div>
			<div class="panel-body">
				<ul>
					<li>
						<b>Professional:</b> your company email. (Eligible to post)
					</li>
					<li>
						<b>Professional's Connection:</b> any email but require a professional to verify (Eligible to post)
					</li>
					<li>
						<b>Others:</b> any other emails. (Not eligible to post)
					</li>
				</ul>
			</div>
		</div>
	</div>

	<div id="login_section" class='row'>
		<div class="panel panel-default">
			<div class="panel-heading align-center">
				Login to your account
			</div>
			<div class="panel-body">
				<form id="login_form" name="login_form" method="post" action="{{url('login')}}" class="form-horizontal"> {% csrf_token %}
					<input type="hidden" class='redirect-field' name='next' />
					{% if login_form.non_field_errors() %}
						<ul class='errorlist'>
					    	{% for non_field_error in login_form.non_field_errors() %}
					      		<li>{{ non_field_error }}</li>
					    	{% endfor %}
					    </ul>
					{% endif %}

					<div class="form-group">
						<div class='row'>
							<div class="col-sm-offset-3 col-sm-8 mini-margin-bottom">
								{{login_form.email.errors}}
							</div>
						</div>
						<div class='row'>
							<label class="col-sm-3 control-label">{{login_form.email.label}}</label>
							<div class="col-sm-8">
								{{login_form.email}}
							</div>
						</div>
					</div>
					<div class="form-group">
						<div class='row'>
							<div class="col-sm-offset-3 col-sm-8 mini-margin-bottom">
								{{login_form.password.errors}}
							</div>
						</div>
						<div class='row'>
							<label class="col-sm-3 control-label">{{login_form.password.label}}</label>
							<div class="col-sm-8">
								{{login_form.password}}
							</div>
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-offset-3 col-sm-8">
							<button type="submit" class="btn btn-sm btn-primary">Login</button>
							<a href='{{url("reset_password")}}' class='pull-right mini-margin-top' id="forgot_password_link">Forgot Password</a>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>

	<div id="divider_section" class='div-center'>
		<h5>OR</h5>
	</div>

	<div id="signup_section" class='row'>
		<div class="panel panel-default">
			<div class="panel-heading align-center">
				Create a Mythdoor account
			</div>
			<div class="panel-body">
				<form id="signup_form" name="signup_form" method="post" action="{{url('signup')}}" class="form-horizontal">{% csrf_token %}
					<div class="form-group">
						<div class='row'>
							<div class="col-sm-offset-3 col-sm-8 mini-margin-bottom">
								{{signup_form.email.errors }}
							</div>
						</div>
						<div class='row'>
							<label class="col-sm-3 control-label">{{signup_form.email.label}}</label>
							<div class="col-sm-8">
								{{signup_form.email}}
							</div>
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-offset-3 col-sm-8">
							<button type="submit" class="btn btn-sm btn-primary">Create Account</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

mythdoor/assets/templates/sites/apps/account/page/password_change.jinja.html
{% extends base_template %}

{% block main_section %}
<div id="auth_section" class="container">
	<div id="password_reset_section" class='row'>
		<div class="panel panel-default">
			<div class="panel-heading align-center">
				Change your password
			</div>
			<div class="panel-body">
				<form id="password_reset_form" name="password_change_form" method="post" action="{{url('change_password')}}" class="form-horizontal">{% csrf_token %}
				  	<div class="form-group">
				  		<div>
				  			<div class="col-sm-offset-4 col-sm-8 mini-margin-bottom">
				  				{{form.oldpassword.errors }}
				  			</div>
				  		</div>
				  		<div>
					    	<label class="col-sm-4 control-label">{{form.oldpassword.label}}</label>
					    	<div class="col-sm-8">
					      		{{form.oldpassword}}
					    	</div>
				    	</div>
				  	</div>

				  	<div class="form-group">
				  		<div>
				  			<div class="col-sm-offset-4 col-sm-8 mini-margin-bottom">
				  				{{form.password1.errors }}
				  			</div>
				  		</div>
				  		<div>
					    	<label class="col-sm-4 control-label">{{form.password1.label}}</label>
					    	<div class="col-sm-8">
					      		{{form.password1}}
					    	</div>
				    	</div>
				  	</div>

				  	<div class="form-group">
				  		<div>
				  			<div class="col-sm-offset-4 col-sm-8 mini-margin-bottom">
				  				{{form.password2.errors }}
				  			</div>
				  		</div>
				  		<div>
					    	<label class="col-sm-4 control-label">{{form.password2.label}}</label>
					    	<div class="col-sm-8">
					      		{{form.password2}}
					    	</div>
				    	</div>
				  	</div>
				  	<div class="form-group">
				    	<div class="col-sm-offset-4 col-sm-8">
				      		<button type="submit" class="btn btn-sm btn-primary">Change Password</button>
				    	</div>
				  	</div>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

mythdoor/assets/templates/sites/apps/account/page/password_reset_done.jinja.html
{% extends base_template %}

{% block main_section %}
<div id="auth_section" class="container">
	<div id="info_section" class="row">
		<div class="panel panel-default">
			<div class="panel-body">
				{% if email %}
					<p> 
						We have sent you the link to reset your password at <b>{{email}}</b>. 
						<br/>
						Please click the link in the email to continue resetting your password
					</p>
				{% else %}
					<p> 
						We have sent you the link to reset your password. 
						<br/>
						Please click the link in the email to continue resetting your password
					</p>
				{% endif %}
			</div>
		</div>
	</div>
</div>
{% endblock %}

mythdoor/assets/templates/sites/apps/account/page/signup_complete.jinja.html
{% extends base_template %}

{% block main_section %}
<div id="auth_section" class="container">

	<div id="signup_complete_section" class="div-center">
		<div class="panel panel-default">
			<div class="panel-heading align-center">
				Complete your account registration
			</div>
			<div class="panel-body">
				<form id="signup_complete_form" name="signup_complete_form" method="post" action="{{url('signup_complete',confirmation_key)}}" class="form-horizontal"> {% csrf_token %}
					{% for hidden in form.hidden_fields() %}
					    {{ hidden }}
					{% endfor %}

					{% if form.non_field_errors() %}
						<ul class='errorlist'>
					    	{% for non_field_error in form.non_field_errors() %}
					      		<li>{{ non_field_error }}</li>
					    	{% endfor %}
					    </ul>
					{% endif %}
					<div class="initial-section form-group">
				  		<div>
				  			<div class="col-sm-offset-4 col-sm-8 mini-margin-bottom">
				  				{{form.name_initial.errors}}
				  			</div>
				  		</div>
				  		<div>
					    	<label class="col-sm-4 control-label">{{form.name_initial.label}}</label>
					    	<div class="col-sm-8">
					      		{{form.name_initial}}
					    	</div>
					    </div>
				  	</div>
				  	<div class="password-section form-group">
				  		<div>
				  			<div class="col-sm-offset-4 col-sm-8 mini-margin-bottom">
				  				{{form.password1.errors}}
				  			</div>
				  		</div>
				  		<div>
					    	<label class="col-sm-4 control-label">{{form.password1.label}}</label>
					    	<div class="col-sm-8">
					      		{{form.password1}}
					    	</div>
					    </div>
				  	</div>
				  	<div class="password-section form-group">
				  		<div>
				  			<div class="col-sm-offset-4 col-sm-8 mini-margin-bottom">
				  				{{form.password2.errors}}
				  			</div>
				  		</div>
				  		<div>
					    	<label class="col-sm-4 control-label">{{form.password2.label}}</label>
					    	<div class="col-sm-8">
					      		{{form.password2}}
					    	</div>
					    </div>
				  	</div>

				  	<div class='large-margin-top'>
				  		{% if signup_request.signup_email_type == "company" %}
				  			<div class='align-center medium-margin-left medium-margin-bottom'>
				  				Your email indicates that you are a working professional. You are allowed to post free ad. Please complete your profile below
				  			</div>

				  			<div class="form-group">
						  		<div>
						  			<div class="col-sm-offset-4 col-sm-8 mini-margin-bottom">
						  				{{form.company.errors}}
						  			</div>
						  		</div>
						  		<div>
							    	<label class="col-sm-4 control-label">{{form.company.label}}</label>
							    	<div class="col-sm-8">
							      		<input class="form-control" id="id_company" name="company" type="text" value="{{signup_request.suggest_company.name}}" disabled='disabled'>
							    	</div>
							    </div>
						  	</div>
						  	<div class="form-group">
						    	<label class="col-sm-4 control-label">{{form.occupation.label}}</label>
						    	<div class="col-sm-8">
						      		{{form.occupation}}
						    	</div>
						  	</div>
						  	<div class="form-group">
						  		<div>
						  			<div class="col-sm-offset-4 col-sm-8 mini-margin-bottom">
						  				{{form.preferred_email.errors}}
						  			</div>
						  		</div>
						  		<div>
							    	<label class="col-sm-4 control-label">{{form.preferred_email.label}}</label>
							    	<div class="col-sm-8">
							      		{{form.preferred_email}}
							    	</div>
						    	</div>
						  	</div>

						{% elif signup_request.signup_email_type == "company_pending" %}
							<div class='align-center medium-margin-left medium-margin-bottom'>
				  				We cannot identify if your email address is company email or not. Please give us more information about you
				  			</div>

				  			<div id="check_company_email_section" class="form-group">
				  				<div>
						  			<div class="col-sm-offset-4 col-sm-8 mini-margin-bottom">
						  				{{form.is_company_email.errors}}
						  			</div>
						  		</div>
						  		<div>
							    	<label class="col-sm-4 control-label">
							    		Is Company Email?
							    	</label>
							    	<div class="col-sm-8 mini-margin-top">
							    		{% if form.company.errors %}
								      		<input type='radio' name="check_company_email" value='{{TRUE}}' checked="checked">
											<span class='mini-margin-left large-margin-right'>Yes</span>

											<input type='radio' name="check_company_email" value='{{FALSE}}'>
											<span class='mini-margin-left'>No</span>

											<input type='hidden' id='id_is_company_email' name="is_company_email" value="{{TRUE}}"/>

										{% elif form.request_approve_email.errors or form.connection_relationship.errors %}

											<input type='radio' name="check_company_email" value='{{TRUE}}' checked="checked">
											<span class='mini-margin-left large-margin-right'>Yes</span>

											<input type='radio' name="check_company_email" value='{{FALSE}}' checked='checked'>
											<span class='mini-margin-left'>No</span>

											<input type='hidden' id='id_is_company_email' name="is_company_email" value="{{FALSE}}"/>

										{% else %}

											<input type='radio' name="check_company_email" value='{{TRUE}}'>
											<span class='mini-margin-left large-margin-right'>Yes</span>

											<input type='radio' name="check_company_email" value='{{FALSE}}'>
											<span class='mini-margin-left'>No</span>

											<input type='hidden' id='id_is_company_email' name="is_company_email"/>
										{% endif %}

							    	</div>
							    </div>
						  	</div>

						  	<div id="company_email_type_section" class='email-type-info-section hidden'>
					  			<div class="form-group">
							  		<div>
							  			<div class="col-sm-offset-4 col-sm-8 mini-margin-bottom">
							  				{{form.company.errors}}
							  			</div>
							  		</div>
							  		<div>
								    	<label class="col-sm-4 control-label">{{form.company.label}}</label>
								    	<div class="col-sm-8">
								      		{{form.company}}
								    	</div>
								    </div>
							  	</div>
							  	<div class="form-group">
							    	<label class="col-sm-4 control-label">{{form.occupation.label}}</label>
							    	<div class="col-sm-8">
							      		{{form.occupation}}
							    	</div>
							  	</div>
						  	</div>

						  	{% if form.request_approve_email.errors or form.connection_relationship.errors %}
						  	<div id="others_email_type_section" class='email-type-info-section'>

						  	{% else %}
						  	<div id="others_email_type_section" class='email-type-info-section hidden'>

						  	{% endif %}
						  		<div class="form-group">
							  		<div>
							  			<div class="col-sm-offset-4 col-sm-8 mini-margin-bottom">
							  				{{form.request_approve_email.errors}}
							  			</div>
							  		</div>
							  		<div>
								    	<label class="col-sm-4 control-label">{{form.request_approve_email.label}}</label>
								    	<div class="col-sm-8">
								      		{{form.request_approve_email}}
								    	</div>
								    </div>
							  	</div>
							  	<div class="form-group">
							  		<div>
							  			<div class="col-sm-offset-4 col-sm-8 mini-margin-bottom">
							  				{{form.connection_relationship.errors}}
							  			</div>
							  		</div>
							  		<div>
								    	<label class="col-sm-4 control-label">{{form.connection_relationship.label}}</label>
								    	<div class="col-sm-8">
								      		{{form.connection_relationship}}
								    	</div>
								    </div>
							  	</div>
							  	<div class="form-group">
							    	<label class="col-sm-4 control-label">{{form.connection_message.label}}</label>
							    	<div class="col-sm-8">
							      		{{form.connection_message}}
							    	</div>
							  	</div>
						  	</div>
				  	
				  		{% else %}
				  			<div class='align-center medium-margin-left medium-margin-bottom'>
				  				Your email indicate that you are not a working professional. You can optionally request a qualitifed users to approve you as their connection to be eligible to post ad.
				  			</div>

				  			<div class="form-group">
						  		<div>
						  			<div class="col-sm-offset-4 col-sm-8 mini-margin-bottom">
						  				{{form.request_approve_email.errors}}
						  			</div>
						  		</div>
						  		<div>
							    	<label class="col-sm-4 control-label">{{form.request_approve_email.label}}</label>
							    	<div class="col-sm-8">
							      		{{form.request_approve_email}}
							    	</div>
							    </div>
						  	</div>
						  	<div class="form-group">
						  		<div>
						  			<div class="col-sm-offset-4 col-sm-8 mini-margin-bottom">
						  				{{form.connection_relationship.errors}}
						  			</div>
						  		</div>
						  		<div>
							    	<label class="col-sm-4 control-label">{{form.connection_relationship.label}}</label>
							    	<div class="col-sm-8">
							      		{{form.connection_relationship}}
							    	</div>
							    </div>
						  	</div>
						  	<div class="form-group">
						    	<label class="col-sm-4 control-label">{{form.connection_message.label}}</label>
						    	<div class="col-sm-8">
						      		{{form.connection_message}}
						    	</div>
						  	</div>
				  		{% endif %}
				  	</div>

				  	<div class="form-group">
				    	<div class="col-sm-offset-4 col-sm-8 mini-margin-top">
				      		{% if signup_request.signup_email_type == "company_pending" %}
				      			<button type="submit" class="btn btn-sm btn-primary">Complete Register</button>
				      		{% else %}
				      			<button type="submit" class="btn btn-sm btn-primary">Complete Register</button>
				      		{% endif %}
				    	</div>
				  	</div>
				</form>
			</div>
		</div>
	</div>

</div>
{% endblock %}